/**
 * Created by Ryan on 2/23/2016.
 */
public enum ErrorType {
    ILL_FORMED_OPERAND, ILL_FORMED_LABEL, INVALID_INSTRUCTION, TOO_MANY_OPERANDS, TOO_FEW_OPERANDS, WRONG_OPERAND_TYPE, LABEL_NOT_USED,
    LABEL_DOESNT_EXIST
}
